<center>
            
            <div className="IteamsMenu">
                
                 <div className="Items" key="001">
                     <div className="items-img">
                        <img src={papas} alt="Papas" />
                        </div> 
                       <div className="item-info">
                           <h3>Papas fritas</h3>
                            <p>Papas fritas con sal </p>
                            <p className="price">250.2 </p>
                            
                          </div>

                  </div>
                  <img className="logo" src={logo} />
 
            </div>
           
            </center>